### PR TITLE
fix(chore): fix sonar code smells

### LINKED ISSUE #52: Fix Sonar Quality Gate
**Describe the bug**
Fix sonar quality gate issues.

**Screenshots**

https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=sourcefuse_loopback4-vault

### PR DESCRIPTION
**Pull request by RaghavaroraSF**
## Description
- Resolving sonar code smells to improve quality gate

Fixes #52 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/services/vault-connector.ts [hunk 1]
```diff
@@ -38,30 +38,36 @@ export class VaultConnector {
       sealedcode: 200,
       uninitcode: 200,
     });
-    if (!health.initialized) {
-      const resp = await this._vaultClient.init(opts);
-      // eslint-disable-next-line @typescript-eslint/prefer-optional-chain
-      if (!resp || !resp.keys || resp.keys.length === 0 || !resp.root_token) {
-        console.error(`Vault initialisation failed ! Response :: ${resp}`);
-        throw new Error('Vault initialisation failed !');
+    switch (true) {
```
Comment (shubhamp-sf) [inline src/services/vault-connector.ts]: using switch is a bit vague here, because general use cases have a variable passed in here and values inside the cases.

Comment (RaghavaroraSF) [reply src/services/vault-connector.ts]: resolved

**Review by shubhamp-sf — APPROVED** [review]
